[quote.epigraph, , Ps. 66:16]
____
Come and hear, all you that fear God, and I will declare what he has done for my soul.
____

== A Short Account of Alice Hayes

It has been in my heart for many years,
to leave behind me a brief relation of the Lord`'s dealings with me,
from my youth up to this day,
for the encouragement of the young to faithfulness
and continual trust and confidence in the Lord,
who is never lacking to those that truly depend upon him,
either in temporal or spiritual mercies.

I was born at Rickmansworth, in Hertfordshire, in the year 1657, of honest parents,
who educated me in the profession of the public worship of the church of England.
My mother died when I was very young; but while she lived, she was a tender,
affectionate parent to me, almost to excess.
One instance of her affection was very remarkable: I being at one time very weak,
and as was supposed nigh unto death, the exercise thereof was so hard to her,
that she fell down upon her knees, and prayed the Lord to take her and spare me;
which he did, for what end was best known to himself.

I continued at home with my father till about the age of sixteen years,
under the sharp government of a mother-in-law,
whose austerity to me made me weary of living with her,
insomuch that I left my father`'s house, and went to service,
that I might live more at peace than I had done.
The Lord in mercy remembered me, and looked upon my affliction in that day,
though I was not yet come to the knowledge of the truth:
and he followed me in those days with his reproofs
in my conscience for the sins of my youth;
which were dancing, singing, telling idle stories, and some other pastimes,
into which youth are too liable to run.
And not being reproved by my parents, nor by the priest, I went on in the same,
grieving the holy Spirit of God in myself;
not yet knowing what it was that reproved me in secret for these things; though,
through the Lord`'s great mercy and goodness to me,
I was addicted to no worse evils in all my life.

Nevertheless, when the Searcher of all hearts came by his light to open my understanding,
and to set my sins in order before me,
and to make known what it was that reproved me for my misspent time, then,
oh! then it was, that the day of Jacob`'s trouble was witnessed.
Oh! dreadful was it to me,
to consider how I had overlooked the reproofs of the Almighty! and often was
I ready to bemoan myself after this manner;--Oh! that I had but had parents that
could have informed me that those things for which I was reproved were evil;
or that those reproofs I often felt in secret were of the Spirit
of the Lord! surely I never would have done as I did:
but neither my parents, nor the priest, taught me any such doctrine;
both of them counting those things but innocent and harmless diversions.
And as for the light, and grace, or Spirit of God, that reproved me,
I had never heard there was any such thing so near me, as I felt it and found it.
Then was I grieved to think the Lord of glory should
have so long knocked at the door of my dark heart,
and waited for entrance,
and that I had so long kept out him who still followed me with his judgments,
and in great mercy to my poor soul, often brought me into deep sorrow.

The consideration of my latter end he laid weightily before me,
and the thoughts of eternity, and the words "`ever and ever,`" laid fast hold of me.
Then, oh! the trouble and surprise I was in,
insomuch that I could not tell what course to take,
neither unto whom to discover my distressed condition.
Sometimes I have gone into company, and striven that way to divert my sorrow,
but that would not do; and then I would seek some secret place,
and there I would fall upon my knees, and pour out my spirit before the Lord,
begging for mercy and forgiveness at his hands.

Now I am about to relate, how the wise hand of the Almighty guided me.
After I left my father`'s house, I went inquiring for a place, and soon heard of one,
where I continued some time, and was well beloved in the family,
and I served them honestly, and in love.
But it may not be amiss to state how I spent my time at my first service,
with relation to religion, which was after this manner: I kept close and constant,
as opportunity permitted, in going to the public worship,
and very often went alone into private places to pray,
and greatly delighted to read the Scriptures, and to get passages by heart;
and when my hand has been in my labour, my heart was meditating on good matter,
and I was very glad that I was from my father`'s house,
because of the quietness I enjoyed.
I was often comforted in my heart in those days, though I knew not from where it came.

As I thus continued in well-doing, according to the best of my knowledge,
the Lord was pleased to appear to me in an extraordinary manner,
and a sweet visitation I had; for I was led into a deep silence before the Lord,
there to wait, and dared not utter words, notwithstanding I had gathered much,
in the brain, of good words and Scripture sentences;
but now I came to see that would not do.
After this manner that time was spent, and a good time it was to me:
it was the Lord`'s doing, and he shall have the praise of it;
blessed be his name forever!

After some time, I went to live at the house of a justice of the peace,
where my first husband and I became acquainted.
But I should first notice,
that I went for a short time to a brother`'s house before I entered into my second service,
and while I was there, heard a report about the neighbourhood of a woman preacher,
greatly esteemed among the Quakers,
and who was to be at one of their meetings not far from my brother`'s house.
Some of the neighbours, in curiosity, had a mind to hear and see,
and asked me to go with them; to which I consented.
When I came to the meeting, it made a great impression upon my mind.
The solidity of the people, and the weighty frame of spirit they were under,
occasioned many deep thoughts to pass through my heart,
by beholding so much difference between their way of worship,
and that of those among whom I went.
After some time of silence, a woman stood up and spoke,
whose testimony affected my heart, and tendered my spirit,
so that I could not refrain from weeping: but, alas! alas! after the meeting was over,
the enemy soon prevailed again, and darkened that little sense I had,
by his instruments without and suggestions within,
so that I went no more to any such meeting for several years.

The time being come to go to my service at the justice`'s, my mistress,
before I had been long with her, would be often saying,
"`This Alice will be a Quaker:`" though still I had no such thoughts;
but through the Lord`'s goodness to me,
I spent all my spare time either in reading or in getting alone,
or in some religious performance,
and continued diligent and faithful to the trust
that my master and mistress reposed in me,
to their satisfaction, and my own too, being well pleased with my place.

It was in this family, as I said before, that I became acquainted with my first husband,
Daniel Smith, who in love made suit to me,
and we continued together in that family near two years.
About the end of that time,
it pleased the Lord to visit me with sore lameness occasioned by a wrench in my ankle;
but for some time longer I continued in my service.

That winter my master and mistress removing to London,
had not occasion for so many servants in town as they kept in the country;
some they dismissed, and my mistress provided a place for me till summer,
when they were to return.
At this place I received hurt, as to my spiritual condition.
Here I had no help towards heaven, but the contrary,
by the ill example of vain and irreligious conduct in that family.
I therefore caution young people to take especial care what company they join,
and to fly from bad associates as from a serpent; for surely it was a sore venom to me,
because it helped to drive good things out of my mind, and forgetfulness of God followed,
which caused me to have many a sorrowful hour, when the Lord brought me to a sense of it.
Blessed be his name, he did not permit me to go on long in this state:
for now my lameness grew worse, and the time came that I was to leave this family,
and to return to my former master, the justice, where I longed to be,
because it was a more orderly family.

I eagerly would have been well of my lameness in my own time,
that I might be able to go through my business; but I found the more I strove for a cure,
the worse I grew, insomuch that I was obliged to go home to my father`'s house,
which was no small exercise, on account of my mother-in-law.
But blessed be the Lord, the day of his love was still lengthened out,
though in judgment, yet mixed with mercy.
Great was my pain in body, and much greater my sorrow of mind: in this affliction,
like Israel of old, I cried to the Lord for help; for now I saw, if he did not help me,
I was undone forever.
As for man`'s help I despaired of it, for I tried many to no purpose,
so that great and many were my cries and prayers to God, to restore me,
resolving to serve him in newness of life.
This was the covenant I was ready to make with him.
Oh! the matchless mercies, and long forbearance of a good and gracious God, to a poor,
distressed, disconsolate, and unworthy creature!

Very remarkable was the faithfulness and constancy of my dear friend, Daniel Smith,
afterwards my husband, who, in all my distress and weakness,
never shrunk in his love to me, but continued constant,
though I was brought to be a poor cripple and went with crutches; and he was a comely,
handsome man, and had now entered upon a farm, where he was likely to do very well,
and seemingly might have had far better matches.
He, like an honest man, never regarded that, but continued firm and constant,
and waited two years to see how the Lord would deal with me; and at the end,
seeing no amendment, proposed marriage to me, and accordingly we were married.
A faithful, tender, loving husband I had in him;
who provided for me all things that were needful and comfortable;
a mercy and blessing I hope I shall never forget;
and his constancy and faithfulness are worthy to be recorded.
The blessing of God was his reward in this life,
and I have no doubt that he is at peace with his and my God.

My lameness in a few months grew better, so that I left my crutch,
and could go pretty well.
But, oh! it was to be lamented, that I missed the way;
for being recovered from my lameness, and grown strong,
living in heart`'s content with a loving husband, and outward things prospering,
I forgot, like Israel of old, the tender dealings and mercies of so gracious a God,
and the promises and covenants I had made with him;
and I gave myself what liberty my unstable mind desired.

Thus I went on for about one year and a half after marriage; when the Lord,
with an eye of pity, looked upon my wretched and miserable condition,
and laid his hand upon me, in order to awaken me out of this false ease,
and by sickness brought me near to death.
Then my conscience being thoroughly awakened,
I beheld my backslidings and disobedience with amazement:
horror and condemnation took fast hold upon me, and the witness arose,
which caused sore distress of mind; and in this condition,
I seemed just about to step out of time into eternity.
I saw, if I died in this state, my portion must be with the unbelievers and disobedient,
in the lake that burns with fire and brimstone forevermore.
And just would God have been, if he had cut me off for my covenant-breaking,
and disobedience: dreadful it was to me, to behold my time so short,
and the work I had to do so great.
Oh! the horror and amazement I lay under, to think how to endure the torment I deserved.
Let the thoughts of this sink deep into the heart of every one who reads these lines,
that they may become prepared, and truly fitted for the kingdom of rest and peace,
when pale death looks them in the face.
Then will it be easier with them than it was with me;
for no mortal can tell the disquiet I lay in for several nights and days,
looking for that dreadful sentence, "`Depart now, for time to you shall be no more.`"
Oh! the fervent cries and prayers I put up to the Lord at this time,
that he would be pleased to spare me this one time more;
and I begged all that came near me, to pray for me.
My cry was, "`Spare me a little longer, and try me once more,
and I will become a new creature.`"

Thus I ventured once again to enter into covenant with the Lord; who,
in great mercy and pity, looked upon me, and spared, and pardoned,
and raised me from the brink of the grave.
Oh! the boundless mercies of God;
how shall they be sufficiently set forth by me! everlasting glory be given unto him;
let all that is within me praise his name.
And forasmuch as it pleased him to hear my petition, and to raise me up again,
and to give me a little strength, a remembrance of that state seized me daily,
and called for the performance of my vows and promises to become a new creature.

And now I began, according to the best of my knowledge, after this manner:
morning and evening I failed not to pray,
and to read the Scriptures and other books which I took to be good ones,
constantly going to the public worship if able;
also resolving to have a care both of my words and actions, and to act justly by all men.
And I thought I would walk very humbly before the Lord,
in order to become a new creature;
for he let me see that it was holiness he called for at my hands,
and that it was my duty to persevere therein, not for a day, a week, a month, or a year;
but if I would be saved, I must hold out to the end.

Notwithstanding I set myself strictly to observe the aforesaid performances,
many months had not gone over my head,
before I found a very strange alteration and operation in me,
the like I had never felt before;
the foundation of the earth within me began to be shaken,
and strange and wonderful it was to me.
I had hoped, that now being found in the aforesaid practice,
I should have witnessed peace and comfort, but behold the contrary; instead of peace,
came trouble and sorrow, wars and commotions; I feared that my condition was such,
that never was the like;
not knowing that the messenger of the covenant was coming to his temple,
even he whom my soul had been seeking; and that he must sit there, that is, in my heart,
"`as a refiner with fire,`" and "`as a fuller with soap,
to clear his own place,`" which was defiled by the usurper,
who had taken up his habitation there too long.
Oh! it was a long time indeed that the Lord of life and glory was kept out of his habitation,
for an entrance into which he had waited and knocked nearly twenty years;
in which time there was much fuel for the fire, and much work for the refiner,
whose skillful, as well as merciful hand, preserved me in the furnace.
The bad part in me was so great, and the good so small,
that I thought all would perish together:
for the heat of that fire in my heart was great and terrible, so that, like David,
I was ready to say, "`My bones are all out of joint;`" and in the depth of my distress,
the enemy was very strong with his temptations.
But oh! the kindness of God to me in that day,
"`for then did succour come in the time of need.`"
The old adversary was strong, and not willing to lose his habitation,
and have his goods spoiled; but Christ, the stronger, overcame him in due time,
and cast him out, and blessed be God, in a good measure, spoiled his goods.
The strugglings that I felt in those times, I hope will never be forgotten;
and my desire is, that these lines of experience may, and I do believe they will,
be of service to some poor distressed traveller, that may have such steps to trace.

I thought, that if I had met with the account of any that had gone through such exercise,
it would have been some help to me.
I searched the Scriptures from one end to the other, and read several books,
but I thought none reached my state to the full.
The third chapter of Lamentations, and many of the Psalms,
and the seventh of the Romans did somewhat affect me at times,
whereby a little hope would arise in the thought that the
writers of these had passed through something of it.
And, oh! the bitter whisperings of Satan, and the thoughts that passed through my mind,
such as my very soul hated! yet such were the suggestions of the enemy,
that he would charge them upon me, as if they were my own.
But the Lord, in his own due time, gave me to see,
"`that he was a liar from the beginning.`"

Indeed, had not a secret hand of power supported me in this my bewildered state,
I had surely fainted, and laid down in the depth of despair.
Day and night were alike to me; there was no flying from the "`presence of the Lord,
and his righteous judgments,`" which pursued me,
and were now poured upon the transgressing nature in me, which had long continued,
and taken deep root.
Now was the refiner`'s fire very hot, in order to burn up the dross and the tin.
Oh! happy man and happy woman, that does thus abide the day of his coming; for sure I am,
"`his fan is in his hand,`" and if men will but submit when he appears,
he will thoroughly do that for them which no other can do,
"`purge the floor,`" which is man`'s heart, where the chaff is to be burnt.

This is the baptism that does people good;
may the Lord bring thousands more through this inward
experience to make an offering to God in righteousness;
for nothing short of it will do, or stand in the great and notable day of the Lord.

After this manner did the Almighty in great lovingkindness deal with me,
his judgments being mixed with mercy to the unworthiest of thousands.
And as I continued in patience, resolving to press forward towards the mark,
various were the inward states I passed through.
Yet by the assistance of the light of Christ, without which,
I had surely fallen in the vast howling wilderness, where so many dangers did attend,
I came to witness in the Gospel dispensation, what Israel of old passed through,
while in Egypt`'s land and by the Red Sea; and their travels through the deeps,
with their coming up on the banks of deliverance;
and likewise their travels through the great and terrible wilderness,
where were the fiery serpents and scorpions, and the drought, wherein there was no water,
as in Duet. 8:15.

Marvellous it is to think,
that I should ever be preserved through these diversities of states,
and that altogether without the assistance of any outward instrument, which,
blessed be God, many now have; for I was still under the hireling teachers,
to whom I very frequently resorted, and readily would I have settled under them.
I was constant in resorting to the steeple-house; but sorrowful I went in,
and so I came out, week after week, and month after month,
seeking among the dead forms and shadows, the living Lord, who is not to be found there.

And well might it be so with me, for lack of the Lord Jesus Christ,
whom my very soul desired more than any outward enjoyment.
I was grieved at my very heart in that day,
to behold the barrenness of both priest and people.
I looked for some fruits of sobriety, especially in the time of worship;
but I saw some light and airy, with actions of pride; others rude and careless;
and some sleeping; and so little solidity, that I was often ready to say to myself,
"`Is there no people that serve the Lord better than these?`"
For I observed with sorrow, that they would be talking of their farms and trades,
till they came to the very door, and again as soon as they came out;
of which thing I thought not well.
But still I continued under my exercise, grievously weighed down, and bowed in my spirit;
wishing in the morning, would to God it were evening,
and in the evening longing for morning.
So great was the horror I lay under, that I often wished I had never been born.

But now it was not long before I came to witness some tenderness spring in my heart,
that had been so long hard.
I could weep in the sense of my lost and undone state;
for as yet I knew not where to look, or wait for the appearance of Christ,
although I had felt all these inward workings and strivings.
And when I felt a little ease or comfort, I felt it within;
where indeed was my grief and wound; though not knowing that God was so near me,
or who conveyed it to my soul.
I thought that God was only in the heavens above the skies;
for the Scriptures were as a sealed book to me, and I knew not that he was so near to me,
as by his light to let me see the outgoings of my mind,
and the very thoughts and intents of my heart.
However, at times I felt a little warmth in my heart, and a breathing to God in this way;
"`Oh!
Lord, make me one of your fold, a sheep of your pasture.`"
These cries to God, and little else, passed through my heart, for many months;
for that was the first good desire he begot in me,
after he led me through judgment for sin.
Then the light, or good Spirit of Christ, which is one,
let me see plainly that I was not in society with his flock: therefore the cry remained,
"`Lord, make me one of your fold,
a sheep of your pasture;`" for as yet I did not see who they were,
nor where they were folded.

But as I continued thus exercised, the Lord was pleased to discover his people to me,
after many mournful nights and days.
But indeed it was a great cross to me, and great sufferings I went through,
before I could submit to be counted "`a fool among
the people of God,`" with whom now I have true unity,
and I bless God for the privilege.

If any should question, and say,
"`How came you to have these people discovered to you by the Lord, as you say?`"
Truly I give you this answer, and in much simplicity and integrity of heart.
As I continued under the aforesaid exercise, it frequently ran through my mind,
"`Go to the Quakers;`" and as intelligible it was to my understanding,
as if I had heard an outward voice.
But I was not hasty to give up to that motion, fearing and doubting,
lest it should be the enemy of my soul, to deceive and beguile me,
and lead me into errors;
and so I continued going to the public worship of the church of England.
At last no peace nor comfort could I find there, but still the voice followed me,
"`Go to the Quakers;`" but I still lingered for the aforesaid reasons.
Then came into my mind that passage in the tenth of the Acts of the apostles,
concerning Cornelius, who had continued a long time in prayers and alms,
and an angel from God was sent to direct him to send for Simon Peter,
who should tell him what to do.
These Scriptures opened plainly in my mind;
but notwithstanding I had enough to reason within myself,
saying in my heart:--As for Cornelius, an angel directed him, but as for me,
what do I see?
(not then knowing what an angel was; which is a ministering spirit:) I only hear,
as it were, a voice within me, saying,
"`Go to the Quakers,`" and I may be deceived if I heed it.
So I strove against the motions of the Spirit of Truth,
not knowing I was under that dispensation,
wherein "`God speaks now to us by his Son,`" in the hearts of his people.`"

Yet such was the mercy and love of God to me,
that in this time of my ignorance and infancy,
he was pleased in great mercy still to follow me: so that I can truly say,
I witnessed the Scripture to be fulfilled, where it is said, "`In the day of your power,
your people shall be willing.`"
It was no less than the power of God that constrained me
to go and hear what sort of doctrine was preached by them,
for I had never but once heard any of those people preach,
and that was five or six years before.
And after long struggling and reasoning, I inquired for a Quaker`'s meeting,
and was informed of the place and day.
I went, not acquainting anybody where I was going;
neither had I opened my condition to anyone, nor could I. When I came to the meeting,
there I saw a small number of people waiting upon the Lord,
and after some time a servant of God stood up,
and declared such things as I had never heard before from any,
whereby my state was fully spoken to; so that I could set my seal to it,
that it was the truth.
The power that attended the testimony reached to the witness of God in my heart;
and a zeal for him was raised within me, by the hopes that were begotten,
through the preaching of the word of truth.

When meeting was over, I went away with joy and gladness of heart,
and my understanding was in some measure opened, and a faith raised in me,
that the Lord had still a regard unto me,
forasmuch as my condition was so plainly opened by a handmaid of the Lord,
whom I had never seen before.
The Lord alone knew my condition in that time;
and as I continued faithful to what he made manifest unto me,
it pleased the Almighty One to make bare his powerful arm for my deliverance,
through the many and various exercises that I met with for the Gospel`'s sake.

Soon after I received the truth, I met with other sorts of enemies,
that the old adversary raised; but forever blessed be the God of my life,
he gave me power and dominion over my inward enemies,
and delivered me also from the outward ones.

My going to meetings being known, both in my family and neighbourhood,
some wicked instruments did the devil raise up, to set my husband against me.
My dear husband, who was so tender and loving to me all our days till now,
grew very unkind, and his love turned into hatred and contempt.
This was very hard for me to bear from one whom I so dearly loved;
but it seemed good to the Lord so to allow it, "`to try me,
whether I loved anything better than himself.`"
Sometimes when I went to dress myself to go to meeting,
my husband would take away my clothes; but that I valued not,
and would go with such as I had, so he soon left off that;
and many other trials I met with from him, which I think not proper here to mention.
One very close trial he put me to was this: he being pretty cool in his temper,
very seriously spoke to me after this manner;
"`Now I am come to a resolution in my own mind what
to do if you do not leave off going to the Quakers,
I will sell all that I have, and pay every one their own, and go and leave you.`"
This came close to my very life; and then also came the saying of Jesus into my mind:
"`He that loves anything better than me, is not worthy of me.`"
Then was I brought to the very proof, whether I loved Christ Jesus best, or my husband;
for one of the two must have the preeminence in my heart.
Now was the time come indeed, for the full proof of my love to God,
"`whether I could leave father and mother, brothers and sisters, yes,
and a husband that I had loved best of all, for Christ and the Gospel`'s sake.`"
This was a trial none can tell, but those who experience the same;
for those relations are very near; and without an invisible support,
the soul cannot be upheld under such trials; but they whose hearts are true to God,
being sanctified and made clean by the washing of regeneration,
are enabled to deny themselves, not of the unlawful things only,
but also of the dearest lawful things, for Christ`'s sake and the Gospel`'s.

My husband waiting for my answer to what he proposed,
after some time of weighing the thing in my spirit, I said,
with a true concern upon my heart, after this manner: "`Well, husband, if it must be so,
I cannot help it;`" giving him to understand,
that I could not let go that interest I had in God, through faith in his Son,
who was come to save me from my sins, by refraining, in compliance to him,
from going to worship God among that people,
whom God so visibly and so fully satisfied me he owned,
and among whom I had felt and witnessed his presence.
Everlasting praises be given to his name, because when hopes had been raised in me,
that through faith in the Son of God, my sins would be pardoned for his name`'s sake,
I could not let go this interest in my Saviour, for the love of a husband,
though nothing else in this world was so dear to me.
Many a sore exercise the Lord permitted him to inflict upon me,
which were as wormwood and gall to me, for the time they lasted.
I received them as from the Lord`'s hand in kindness,
to try how constant I would be in my dependence upon him alone, when all in this world,
that were near and dear to me, were turned against me: yes, father and mother,
brothers and sisters; but nothing came so near me as my husband.

When I came truly to take up the cross for Christ`'s sake,
I met with persecution of various sorts;
but that of the tongue was the hardest for me to bear, and a large share I had of that,
with cruel mockings.
But thanks forever be to that power who upheld me through all gross abuses,
false reports, undervaluings, and slightings; the very remembrance thereof bows my heart,
and humbles my spirit, in the sense of the kindness of God to me in that day,
who enabled me with patience to go through all the clamour of their tongues,
till it pleased the Lord to remove out of my way many of my persecutors and slanderers,
some of whom I may have occasion to mention.

It being spread about that I was turned Quaker, the priest of the parish,
whose name was John Berrow, hearing of it, came to give me a visit.
Among the rest of his discourse and reasonings with me,
he was so hardy as to venture to tell me, that the Quakers denied the Scriptures,
and the resurrection, and the man Christ Jesus, who died outside the gates of Jerusalem;
and that they only believed in a Christ that was in them.
To which I answered, No, they do not say so, nor preach such doctrine.
To which, he replied, "`It may not be yet, till they have got you.
You do not discern the hook, or the pill that is gilded:
it is a dangerous doctrine they hold, and damnable heresy they are in.`"
To which I only replied, "`If they deny Christ,
I never will be a Quaker;`" and so he went his way.
And after much labour both of body and mind, in searching the Scriptures,
and comparing their doctrine and principles therewith, I found him to be a false accuser.

Some years after, I found a weighty concern upon my spirit,
to go to his public place of worship, and charge him with this falsehood,
to clear the professors of the truth, and my own conscience;
more of which I shall hereafter have occasion to mention;
and shall now proceed to say something concerning those instruments before hinted at,
who were the authors of much disturbance to my dear husband, and exercise to me.

A cook-maid that lived with the justice, whose servant I formerly was,
and a servant maid of my own, being both of a bad spirit,
mattered not what lies they made and reported of me;
but the Lord discovered their wickedness, and my innocency, in his own time.
My maid, by her stories and deceitful carriage to the justice`'s family,
thought to have preferred herself there,
knowing it pleased the justice`'s wife to hear stories concerning me,
because of the dislike she had to the Quakers;
but in less than six months after she went from me, she was found to be a thief,
and ran out of the parish, and I never saw her more.
As for the cook-maid, she in a very short time came to much poverty,
and often afterwards I relieved her.

Two others were very sour to me, the justice`'s wife, and my husband`'s mother.
The two before mentioned had so filled them with bitter unkindness towards me,
that they very much hurt my husband, by setting him against me.
The justice`'s wife especially caused me to go through much exercise; but, however,
it lasted not long, for in a few months after I was convinced of the truth,
she went to London, where she stayed some time.
The time of her intended return being come, and the coach provided to fetch her home,
death struck her, and she was brought home dead.

My husband`'s mother being very full of wrath and bitterness towards me,
I thought to have pacified her by entreaty,
and by acquainting her a little with some part of my exercise,
and that I did not go to the Quakers in a stubborn mind, or self-will,
nor with any ill design of undoing my husband, as some reported.
But when I began to speak to her, she flew into a bitter passion,
grievously reflecting upon me, saying I would undo her child, meaning my husband.
I could by no means gain her into any moderation, nor would she hear what I had to say,
but departed from me, expressing herself in much anger after this manner:
"`I will never endure you any more.`"
She went home, where she soon fell sick and died,
and was buried in less than a week`'s time.

But the enemy soon stirred up another, my husband`'s father-in-law.
He came one time, full of prejudice against me, to our house,
and brought a great book with him, and sat down.
My husband soon came in, when they both set upon me, reflecting upon the Quakers:
whereupon I attempted to go out of doors, but my husband prevented me,
for he placed himself by the door, to hinder my going out.

In those days I could not talk or contend much for the truth; but blessed be God,
I was made willing to suffer for it many ways; but that which was hardest for me to bear,
was from my husband, whom I loved as my own life.
We had not then been married above two years, so that if God had not upheld me,
I had fainted.

My husband not permitting me to go out as I intended,
the great book was laid upon the table, and they said, if I lacked a book to read,
there was one for me to look in, and urged me to read it.
I took it, and read awhile to myself, but I soon shut it up, and would read no more.
I saw it to be written by an adversary to the truth;
and I then took up the Bible in my hand,
and the first place I cast my eye upon was that passage in the Psalms, where it is said,
"`It is better to trust in the Lord than to put confidence in man; yes,
it is better to trust in the Lord than to put confidence in princes.`"
Oh! the comfort I felt in reading it!
It was more to me than any outward treasure, for I found my strength renewed,
and patience given me to bear all, and suffer quietly.

My father-in-law used many bitter expressions, saying, that if he were my husband,
he would never see me want; insinuating that he would leave me;
my husband being then present,
and having himself before threatened me with the same thing.
Then my husband`'s father-in-law began to curse and swear,
for which I could not forbear reproving him, in the plain language;
which so enraged him that he was like a madman, cursing, and saying;
"`Do not thee and thou me;`" and in a despising manner, he said,
"`A Quaker! away with it: if you had been anything else; had you been a Baptist,
and gone to hear them every day in the week, it had not been so bad as this.
A Quaker! away with it.`"
And again: "`If you will not turn from your religion, I will buy a chain,
and chain you to that maple tree that stands in the green;
and there you shall be glad to turn for hunger.`"
More might be mentioned, which I omit for brevity`'s sake;
but my poor husband said not much at that time, only kept me within doors,
to see and hear what his father-in-law could do with me.
But blessed be the Lord, it did not move me;
and let all be encouraged to trust in that ancient arm of power,
that never failed in time of need, nor ever will,
those that have a single eye to his glory.

It was not long before the Lord brought them both to a sense of their error;
for the next time they met, my father-in-law told my husband,
he was very sorry for what he had said and done to me,
and that he would never do so more; neither indeed did he,
but ever after was very loving and moderate to me.
And such an impression was made upon him,
that he became very moderate and respectful to all Friends with whom he conversed.
Afterwards my dear husband`'s love returned,
and he continued to his life`'s end a loving and tender husband,
and an indulgent father to our children: and through the Lord`'s goodness to him,
he was convinced that it was the truth for which I suffered.
And I do believe he died in the faith, and is at rest with his God; for which,
and all his mercies, let all that is within me give him the praise.

Having been made an experimental witness of the dealings of the Lord,
and passed through several states,
it pleased the Lord to make me instrumental in his hand, to speak a word in season,
both in public and private, to others;
and in my obedience to the motion of the Spirit of God, I found peace and strength,
and encouragement to persevere.

But I may first make a little observation upon the deceitful spirit by which John Berrow,
the priest of the parish of Watford, was led, which I beheld, to my grief and sorrow,
insomuch that I felt a concern upon my spirit,
to go and reprove him publicly in his worshiphouse,
for his false accusations--as that the Quakers denied the Scriptures,
and the resurrection, and the man Christ Jesus, that died outside the gates of Jerusalem;
and that they only believed in a Christ within them;
and for his going about from house to house,
to discourage well-inclined people from going to a Quaker`'s meeting.
For he found the people declining from him;
as at that time a good thing was stirring among them,
and many were inquiring after the kingdom of heaven.

For these reasons, I found a great concern upon my spirit, that the way of the Lord,
and his people, might not be misrepresented,
and that the honest inquirer might not be turned out of the way.
As this had rested long and weightily upon my spirit, I often cried to the Lord,
to enable me faithfully to discharge that which I saw he required at my hand.
The concern was weighty, and I was not forward,
lest I should be found to run before I was sent;
therefore I waited patiently to be fully satisfied in the matter, not only a day,
or a week, but many months; and as my concern grew heavier upon me, I gave up,
begging the Lord to be with me, and to give me a full mission for so weighty a service.
It pleased the Lord to confirm me in it several ways; notwithstanding,
as poor Gideon of old, I presumed to prove and try the Lord once more.
So I said in my heart: "`Oh Lord! if you will be pleased to send your servant,
Francis Stamper, to this town tomorrow, then I shall be confirmed.`"
I had not as yet told anybody what I had to do,
and it pleased the Lord to grant me my request.
On the morrow, which was the 31st of the eighth month, 1696; when meeting time came,
and Friends were going, Francis was not yet come; but I had faith to believe he would.
As I was going to meeting with some Friends, I said to them that I would go back,
and tarry for Francis Stamper; whereat the Friends smiled,
because he was but lately come home from a long journey.
I waited but a little time before he came, and soon after he went into a Friend`'s house.
I very well remember his words: "`Oh! how has my spirit been dragged here:
I was late last night at London, but must go to Southgate.`"
There he had a country-house, and the watch was set when he came out of London.
I took good notice of his words, but said nothing to him of my concern,
till after meeting; when coming to a Friend`'s house, I told him what I had to do,
and I asked him if he would go with me.
To which he answered, after weighing the thing in himself, "`I may go with you.`"

In the afternoon we both went to the steeple-house,
and sat down in the alley against the priest,
and waited till he had done his sermon and prayer.
Then I stood up, and said to the priest, "`Neighbour Berrow,
I have a question to ask you,
and I do desire you and this assembly to hear me;`" but he would not, and hastened out,
without hearing what I had to say.
Seeing him go so hastily away, I applied myself to the people, and said:
"`John Berrow came to me and said,
that the Quakers would tell me that I must deny the man Christ Jesus,
who died without the gates of Jerusalem,
and that I must believe only in a Christ that was within me.`"
And I bore this testimony to all present at that assembly, saying,
"`We do acknowledge the Scriptures; and do say,
and believe that there is no other name given under heaven, whereby any can be saved,
but the name of Jesus Christ, who died outside the gates of Jerusalem, and was buried,
and rose again the third day, and now sits at the right hand of God,
glorified with the same glory which he had with the Father before the world began.`"
Then I stopped, and Francis Stamper stood up,
and would have said something to the people, by way of advice;
but one of the churchwardens with some others, came and compelled us both to go out.
I stepped upon one of the seats, and acquainted the people,
that we should have a meeting that evening at our meetinghouse,
where all who were so inclined might come; and blessed be God,
a large and good meeting it was,
where the glorious presence of the Most High was with us, and among us.
And good service for his God had that faithful servant, Francis Stamper, that evening;
as also at many other times here, and in these parts,
where a great openness was among the people, and many were convinced.
In a fresh and lively remembrance of this faithful servant of the Lord,
a testimony springs in my heart to leave behind me:

He was a man given up in his day, faithful to his God;
and ran to and fro on the earth for God`'s honour and the good of souls; rising early,
and lying down late.
He was industrious in God`'s vineyard and harvest-field,
for the Lord had made him a skillful and laborious workman, and a valiant soldier,
who feared not the great and potent adversary.
Eminent was that power, which did attend this man of God, my friend and brother.

I esteem it a mercy from the Lord,
that I had the privilege of being well acquainted with him in the service of truth,
as well as in meetings.
I, with many thousands more, have been refreshed under his living testimonies,
which have dropped upon the tender plants like dew,
or the small rain that nourishes the tender blades.
Oh! the remembrance of it often affects my heart:
and the Lord greatly blessed his labour of love;
for by the power that attended his ministry, many were turned "`from darkness to light,
and from the power of Satan to God.`"

He was a man of a tender spirit, and though not advanced in years,
was as a nursing father.
Many are witnesses how ready and willing he was, upon all occasions, to go at any season,
to visit those who were in distress, either in body or mind,
having a word suitable to their several conditions:
and often was the broken heart bound up, and the sin-sick soul encouraged.

Great was the sorrow and mourning for the loss of such an instrument;
but not as without hope.
My hope is firm in the living God,
and I have faith to believe that he will raise up
to himself more witnesses and faithful labourers,
in the room of those he has been pleased to remove
and take to himself out of this evil world,
as he has done this his servant, who is gone in peace,
and has entered into that rest which God has prepared for the righteous.

In the close of this short testimony for my dear friend
and fellow-labourer in the work of the ministry,
I must say, it is of the Lord, and he is worthy to do whatever he pleases.

All that he does is well done, whether he gives or takes away,
blessed be his name forevermore.

Alice Hayes.

After the Lord had tried me with exercises of various sorts,
he was pleased to prove me further by persecution for tithes,
both in the spoil of my goods and by imprisonment.
I was taken from my farm and family, having five fatherless children,
and was committed to Alban`'s jail,
where I was kept prisoner about thirteen or fourteen weeks,
and had several score pounds`' worth taken from me in corn and cattle,
by the priest and impropriator, because for conscience-sake I could not,
in this Gospel day, pay to support that worship,
neither that antichristian yoke of tithes.
A testimony lives in my heart, to encourage all those who are convinced of God`'s truth,
to be faithful in this matter,
and in all things which the Spirit of Jesus Christ shows them to be evil.

I mention my sufferings, not in a boasting way, but for the encouragement of the weak;
for he that bore up my head under all my trials and exercises,
will bear up every sincere and honest soul, that desires faithfully to do his will.
I bless God in my very heart that he has counted me worthy to suffer for his namesake;
and of a truth I can say, He never permitted any exercise to attend me,
but he assisted me with power and patience to go through it;
and his word have I witnessed to be fulfilled, a husband he has been to me,
and a father to my fatherless children.

It is my desire that all, both rich and poor,
may be faithful to God in all his requirings, with respect to tithes,
whether to priest or impriator, for they are all one in nature and purpose,
and are demanded and recovered by the same law, that is, the statute of Henry the Eighth,
an old popish law, whereby they sue "`for God and the holy church.`"

Forasmuch as we are now under the Gospel dispensation,
wherein God has begun to work by his great power,
against that spirit of antichrist that denies the coming of the Lord Jesus Christ;
my faith is, that he will bring down that antichristian yoke of tithes,
under which his innocent people have long suffered.

I further believe,
that had all been faithful who have been convinced of the evil thereof,
and stood firm to their testimony,
by patiently suffering in the "`meek spirit of the Lamb,`" that ravening,
devouring spirit, had been well nigh famished;
and the consumption determined by God Almighty,
would have been much more on that spirit of persecution by this time.
But, oh! as it was of old, so it is now, unfaithfulness makes the work go on slowly,
and the journey more tedious.
But, blessed be God,
there is a small remnant who are fully given up to follow their true Shepherd,
Christ Jesus, who is come in the power of his Spirit, and is revealed in a remnant,
who are thereby enabled to stand as witnesses for God,
against all hireling preachers and time-servers; for his purpose is,
to set his Son on the top of all hills, and mountains of show, and shadows of religion.
It is my belief, that by the assistance of that grace which is come by Christ Jesus,
many more will be raised to bear witness to the free ministry of the Lamb of God;
and happy, yes, thrice happy, will every one be, who serves God with all his heart,
and all his outward substance too, if He calls for it.
Oh! let no one withhold anything the Lord requires, but remember,
"`the earth is the Lord`'s, and the fulness thereof;
and the cattle on a thousand hills are his, and he knows what we need.`"
If a time of stripping from these outward enjoyments is permitted,
it is but for a trial of our faith.
Oh! that not one who may be deeply tried, may faint, or distrust the Lord,
"`whose care and whose eye is over the righteous,
and whose ear is open to their prayers.`"
And as all come to trust in his name, the God of Israel will care for them,
and appear in a way and by a means they think not of;
so that he will be found "`a God nigh at hand,
and a present help in every needful time.`"
Therefore, let all that fear his name trust in him; "`for the life is more than food,
and the body more than clothing;`" and to every one that trusts in him,
he will give "`life for the soul,
and bread for the body;`" as he has done for me in a wonderful manner.

Here it may not be unfit to mention something of my own suffering
on the account of impropriation,^
footnote:[Impropriation was the collection of money from a parish that was paid to a
layman or lay corporation that owned the lands of the church or ecclesiastical living.]
for the information of some who have heard a report thereof, and may be misinformed:
for I am concerned that none may be deceived, and say,
or do that which may bring trouble upon themselves;
for some have taken the liberty to reflect upon me on the one hand,
and some on the other.

The impropriation of Watford seemed to differ from most, if not all in England,
in this particular; it was a dowry of the lady Essex,
and no part of it either belongs to church or priest;
and through ignorance Friends scrupled not to pay it,
not knowing it to be the same as tithes in its nature and purpose,
and that it is upon the same foundation as other tithes,
and granted and maintained by the same power, and recovered by the same law.
I say, we ignorantly paid it, till it pleased the Lord to open our understandings.
It was customary with the collectors of this impropriation,
to contract with us who rented farms, for so much money to be paid yearly;
and the contract which my husband had made and signed with the collectors,
some time before his death, being now expired, they came to me to renew it with them,
to which I consented.
But after it was done, a fear possessed me,
lest I had done what was not right in the sight of God,
and much reasoning I had in my mind about it.
The concern grew heavier upon my mind,
and in great fear and trouble I continued many days and weeks,
earnestly crying to the Lord for a clear understanding of his will,
concerning this matter of impropriation.

On the other hand, a fear was upon my heart,
lest I should do that which the Lord required not at my hand;
and thereby bring sorrow and sufferings upon myself and family,
and not find peace in the end.
Great was my trouble, and many nights and days of sorrow I had,
which brought me very weak in body, near unto the grave.
To suffer for suffering sake I never desired; and to suffer for well-doing,
the Lord knew my heart to be wholly given up to his will: only I cried, "`Lord,
let me be fully satisfied that I suffer for well-doing!`"
This was my earnest supplication; and in his own time,
he was pleased to answer my prayers, and fully satisfy me: and I bless God,
who gave me power cheerfully to go through all my sufferings upon that account.

I would have all know, that I had no other end, but God`'s honour and my own peace,
which I valued more than all outward enjoyments that this world can afford.
This is a sincere account why I paid, and why I refused;
let the judgments of men be what they will, I have peace with my God,
and he shall have the praise forever.

The way in which it pleased the Lord to satisfy me herein, was after this manner:
I got a few Friends together to have the matter of impropriation fully discoursed upon;
and there were two sensible Friends who discoursed upon the subject,
the one for paying it, the other against it.
He who was for paying did not then see it to be the same as the tithe,
because it paid no priest, nor any part of it belonged to the church of England;
but the other Friend so plainly proved it to be a branch from the same tree,
that I was fully satisfied, and so were all the rest who were at the meeting;
and the Friend who opposed the other,
was himself convinced and afterwards refused to pay it,
and faithfully suffered for the same.

[.asterism]
'''

The greatest part of the foregoing was written some years ago;
and having since seen much of the wonders of the Lord in the deep,
I find a concern upon my mind, to add something as the Lord shall enable,
for the encouragement of my offspring, for whom I travail in spirit,
and for all the babes and lambs of God, and for the mourners in Zion, who go heavily on.
For the sake of these,
I am made willing to say a little more of the kindness
of God to the workmanship of his hand,
and to call to faithfulness from a deep sense of the need there is of it.
And I may say, in the bowedness of my spirit, that I have no might of my own, nor power,
nor ability, but what he shall be pleased to give me:
and let nothing be attributed to that monster, self,
which too often appears both in preachers and writers,
and proves like the "`fly in the ointment of the apothecary.`"
I do heartily pray that I may wash my hands in innocency,
and be preserved clean from that fault; that God only, who is the Author of all good,
may have the praise, from me and every creature that has breath.
Wonderful have been his favours and mercies to me above thousands:
one half of his mercies I am not able to set forth.

What I have seen and felt this year, 1708, is unutterable,
being a year wherein I was "`led into the deeps,`"
and beheld much of the wonders of the Lord,
more abundantly than I am able to express;
neither indeed do I as yet see it required at my hand;
therefore I shall only give the Lord his praise, and admire his wonderful doings,
for I can truly say, "`it is marvellous in my eyes.`"

When very weak in body, I have been led by the Spirit in the low valley of deep humility.
Surely, as there is a coming into near communion with Christ the Lord,
there will be a very great abasement in the creature,
and all flesh will be brought to silence in his presence, that his voice may be heard,
and his goings seen in the temple, with what majesty he appears there.
Oh! excellent it is,
and very glorious to behold! and that my soul may dwell before the Lord
is what with great humility and tears I beg at his bountiful hand.
In the living faith that crowns with victory, I have a hope in me,
that as I continue in well-doing to the end, for his Son`'s sake,
I shall arrive at the desired port and haven of rest,
where all the righteous sing hallelujah forevermore.

It pleased the Lord to make known his truth to me, about the year 1680,
by that servant and handmaid of the Lord, Elizabeth Stamper; and without boasting,
I can truly say, from that time to this,
I have been very careful to obey his holy mind and will,
as it has been made manifest to me.
And for the encouragement of others to faithfulness, I have not, since I knew the Lord,
been one day without his presence, more or less; so that, blessed be God,
I have had no complaining in my streets; for I have said, and do say,
if there was no future reward, the present comfort of obedience,
is sufficient encouragement to the children of men to fear God,
and keep his commandments.
Those who do, may well live thereby; that is, by the life of the Son of God;
for he is come indeed that we may have life,
and it is in obedience that the aboundings of it are known.
And this great kindness of God to mankind, is not by any merits of ours,
but of his great mercy for his Son`'s sake.
Through his precious blood we have all these great
benefits which do accrue to both soul and body,
in our submission to his yoke, and in learning of him, who was the pattern in every age.
Moses, in the mount, did his work according to the pattern, by the wisdom of our God;
and David, his servant, gave orders unto his son Solomon and the elders,
how to carry on and build that great house which was glorious in its time.

How much more glorious is this dispensation of light and grace,
which shines from the Son himself, the express image of the Father, into our hearts;
whereby we may now see our way, and follow the pattern,
and need not stumble where thousands have fallen!
Some have stuck too fast in forms and shows of good things, which were but shadows,
because they will not come to the substance, the pattern by the Spirit,
which is sufficient to teach all things necessary for eternal salvation.
Therefore, if men will stumble here, it must be,
"`because they love darkness rather than light,`" and to be spiritually in Egypt,
a slave under Pharaoh, than to come where light and good are to be enjoyed.

Oh! what shall be said to stir up the sons of men, that they may be awakened,
and no longer sleep in the bed of ignorance?
Arise, and come away to the school of Christ,
who is this pattern of whom I have been speaking.
A measure of his own pure Spirit he has given to every one; that they may learn thereby,
and read inwardly, and ask so as to receive.
For what is asked by faith, and in the measure of his Spirit,
he will surely answer in his own time.
And as times and seasons are in his hands, so he, in his wisdom,
knows when it will be best to deliver the creature out of trouble,
and bring honour to his own name, who is worthy of all praise;
for he is an all-seeing God, and no affliction or trouble can be hid from him.
Yet he will be sought unto and waited on; and they that know him will trust in him;
for these know him "`to be a God at hand,
and a present help in the needful time,`" as my soul has witnessed:
glory to his worthy name forevermore.

Oh! you into whose hands these lines may come, be in earnest for your soul`'s welfare,
while health and strength of body are afforded.
Seek God with all your hearts; that you may come to the knowledge of the truth,
as it is in Jesus Christ; and witness an acquaintance with him,
by waiting on him frequently.
Then, when the time of weakness takes hold upon you, and no worldly means will avail,
you will know the angel of his presence to stand by you till death:
this will be more joy than ten thousand worlds at that hour.
Oh! the strength of love! surely the love of God is to the children of men,
that they may prize time while they have it,
and make all things ready that appertain to eternal life.
This is to answer the end of our being, which is "`to glorify God,
and to work out our own salvation with fear and trembling,`" which must be done, if ever,
in the time afforded unto men in this world.

Therefore be wise, you children of men, and come and learn of Christ, and follow him;
for he ever gained the victory, and has all power in heaven and earth committed to him.
Resolve, by the help of his grace, to follow on wherever he will lead you: for assuredly,
he will give you power to tread on scorpions, and to keep under you every foul spirit.
And in your obedience you will be watchful in the light,
by which you may see every appearance of evil; resist it by the assistance of the Spirit,
and not give it any entertainment.
Remember that you are soldiers under the banner of the unconquered Captain, Christ Jesus,
who always stood by his own in every age;
so that in faithfulness they went out of this world, though it has been a field,
where the saints and martyrs have sealed with their
blood their testimonies for our God and the Lamb,
who was their Captain, and brought them off with victory, bearing his mark.

Oh! who would not be a follower of the Lord, who can help both outwardly and inwardly,
all those that stand for him and the honour of his name; whose name is a tower of safety,
and has stood, in his own power,
against all the instruments that the devil has raised
in every age to push at the children of God!
In every dispensation the bad have troubled the good; yes,
the lion is still for tearing the lamb, and the wolf is hunting for his evening prey.
But glory be to God, the true Shepherd is known, and his power felt,
in which the righteous have trusted to this day.
And the living can now say,
It is the same as it was in the beginning--a canopy over the righteous,
and a safe hiding-place in time of trouble, when instruments of cruelty are let loose,
and greedy to do mischief.

Such as swear, or lie, or cheat, or commit adultery, or lead a life in any other evil,
let me prevail with them to repent, and forsake the evil of their ways,
and the sins that so easily beset; and do the devil`'s drudgery no longer.
He is an ill master, and the wages that he gives are such as he has for his own doings.
Therefore, all you who are at a distance from God, by reason of evil,
put it far away by true and timely repentance,
that you may know what it is to be "`washed with the water of regeneration,`"
and cleansed from sin by the blood of the Lamb.
So may you witness the renewings of his favour, which will be as the balm of Gilead,
that will thoroughly heal the wound, and make you strong,
and fit for the service of Christ our Lord:
he is the best Master that ever man or woman served, and gives eternal life.
But all who come to him,
"`must believe that he is a rewarder of them that diligently
seek him,`" and they cannot serve two masters.
They must renounce the devil, their old master, and all his works,
with the pomps and vanities of this world, and, like good soldiers,
follow the Captain of their salvation, in all perseverance,
through good report and bad report, and keep to the standard--the Spirit of Truth.
If you do this you may pray to the Giver for what you stand in need of,
let it be bread for soul or for body, or for faith, or hope, or courage,
or the armour of light, or whatever else your needs may be.
Take courage and ask,
and you shall receive double comfort for all you
undergo for Christ`'s sake and the Gospel;
and for the life which you have lost, which you had in vanity and evil,
you shall find a life a hundred fold exceeding,
in peace and inward joy by the Holy Spirit.
Submit to the will of God, who has called you with a high calling,
that you should hear his Son, and obey him in all things unto the end.
Then be good soldiers like that blessed apostle, who fought the good fight,
and kept the faith.
Oh! faithful soldiers! come on, and be not fearful or fainthearted,
for a woe attends such; but be valiant and zealous for truth on earth,
according to that knowledge which God shall give you.
Be found improving your talents, whether they be five, two, or one; however small it be,
your hearts being seasoned with the grace of God, your delight will be in his treasury,
and you will witness an increase in that which will do you good in the end of your warfare,
be it long or short.

In faithfulness all will end well.
God`'s care over his children and people is the same in every age.
I am a witness of it, a poor worm, an unprofitable servant;
for if I have obeyed his command, it is but what was, and is, my reasonable duty.
The Scriptures are verified, where it is said; "`His eye is over the righteous,
and his ear is open to their cry;`" for he is the God and Father of mercies,
and delights to meet with his own to do them good.
He takes no pleasure in afflicting the children of men,
further than to bring them into subjection to his Son;
and that they thereby may come to know the state of sonship,
and learn submission to his heavenly will.
His will is, that all men everywhere repent, and come to the knowledge of the truth,
and be saved with an everlasting salvation; saved from sin,
and from the wrath due to the same.
This is freedom indeed, to be made free by the Lord of all power, who said to the Jews,
"`If the Son make you free, then you are free indeed.`"

Oh! that men would strive for this freedom,
and believe in the sufficiency of that grace that is come by Jesus Christ,
and appears in the heart to convince of sin in its first budding!
By the strength of this grace, it may be crushed as the cockatrice egg,
and be cast out by the assistance of the spirit, which is one with the grace of God.
The effect of the grace and coming of Jesus, is indeed to save people from their sins;
and to them who will be his,
and believe that he has all power committed to him in heaven and earth,
and had the victory over the world, the flesh, and the devil, he can,
and does give power.
Stronger is he that is in us, that is, Christ by his spirit,
than he that is in the world; and more powerful is Jesus to save,
than the devil is to compel men to sin; for he can but tempt.
Yielding to his temptation brought misery upon our first parents;
and yielding is the cause of misery still.

The second Adam, the Lord from heaven, the Restorer of mankind, did not say,
that we should not be tempted, or have no onset in the field, where this usurper goes,
and has his food--the earth and the dust thereof.
He that was so bold as to approach and tempt the Lord of glory,
will no doubt assault his followers: and the Lord,
who well knew what we should meet with, advised and counselled to watch and pray,
that we enter not into temptation; which was as much as if he had said,
"`If anything that is evil trouble you, touch it not; but pray to me,
and I will assist you:`" so that it is the Lord who works this deliverance.
God must have the praise, who is worthy, for his own works praise him,
because they are wonderfully made manifest in this age of the world,
after so long and dark a night of apostacy.
Blessed be God, who is the Spirit of light and of purity,
and has now eminently broken forth by his Son to
enlighten the children of men in the heart.
His spirit and great power has been stronger than the power of darkness,
pulling down and spoiling the works of the old adversary, yes,
and binding and casting him out; fitting the creature for his heavenly building,
to be as a stone or a pillar in this his latter house,
which God is building of living stones,
disallowed indeed by the worldly wise of this day, but approved of God,
who is the Chief Corner Stone, and Lord of all.

We read of some of old, who said, "`What shall we do, that we may work the works of God?
And the answer was by one who well knew: "`This is the work of God,
that you believe in Him whom God has sent.`"
Oh! it is a matter of sorrow,
to think that men and women should be so backward in their belief on the Son of God,
in his spiritual appearance in the heart; but blessed be God, a remnant have believed,
and thereby can cry "`Abba, Father,`" because he has done that in them, and for them,
by the operation of his mighty power, which no other could do.
Thereby we know that the Son of God is come and has given us an understanding,
that we may know Him that is true, even Christ in us, the hope of glory;
which is as an anchor, sure and steadfast, and never failed when the wind blew,
or the rain descended, and floods of affliction swelled high.
No, no, it never failed, for the foundation is a tried one,
a rock immoveable in every age.
All that have built on it, and so continued, have stood fast and sure;
while those who have built upon the sand have suffered great loss,
when time has come to an end, and their foundation has been tried,
and found to be but sand.
Oh! it will be dreadful to go out of time into eternity, in the displeasure of an angry,
yet long-suffering and just God; who will be just in all his ways,
and render to the foolish virgins and sandy builders, and slothful servants,
a reward according to their doings, even the sentence pronounced in the Scripture;
"`Depart from me, you workers of iniquity, I know you not.`"
It makes my heart melt within me, to think how dismal a state it is,
to be banished from the presence of a glorious God,
who long strives with men by his good spirit.
But how is it to be lamented, that by far too many have refused the offers of his love,
and have chosen their own ways, and hated to be reformed!
Therefore, great will be the condemnation of such, and dreadful will the worm gnaw,
when they consider how time is over, and all means of grace are gone.
Then shall such see how they have missed the favour of a good God,
by choosing their own ways, and doing their own work.
Oh! lost time, the field, and the pearl also!
Therefore, better will it be to mind the work of God, that by faith in the Son,
you may witness him to work all your works in you, and for you, of his own good pleasure.
There is nothing for man to boast, or glory in;
he is to be pliable as the clay in the hand of the potter,
till he is made a vessel to his praise.
God has no delight in the death of him that dies,
but rather that men should obey his commands and live; or surely,
he would not set life and death, good and evil, before them, and say, "`Choose.`"
This seems to render it very plain, that there is a choice for mankind,
and an offer of salvation while in this world; so that men and women may choose life,
by believing in Christ; or refuse it, by unbelief,
which leads from God and the Lord Jesus, into death and darkness.

But blessed be God, who has brought a remnant to the knowledge of his light,
and to obedience also; such are made living witnesses of the sufficiency of his grace,
like the apostle of old, who, when in great buffetings and temptations,
found it effectual; though we find he had been in a state, whereof he cries out,
"`Oh! wretched man that I am, who shall deliver me from the body of this death?`"
And again, "`I am carnal, sold under sin.`"
This was a mournful state with Paul for a season: when sorrow possessed his heart,
he cried to God, who was able to help him,
and in due time he came to witness the sufficiency
of his grace to bring him out of that state,
to know a better condition, and to say,
"`There is therefore now no condemnation to them that are in Christ Jesus,
who walk not after the flesh, but after the spirit; for the law of the spirit of life,
in Christ Jesus, has made me free from the law of sin and death.`"
Oh! the blessed freedom that came to believers in that early day, by Jesus Christ;
and blessed be God, it is the same in this day as it was then; for this grace,
which is come by Jesus Christ, does not only enlighten men and women,
to let them see their sinful condition,
but gives power to the soul to help it out of thraldom.
And as there is faithfulness in the creature,
the sufficiency of the grace is still witnessed,
to lead from one degree of strength to another: so that here they have to thank God,
as the apostle did, and can say, "`In Him there is no variableness,
nor shadow of turning,`" for he is the same as ever,
to those who believe and follow Christ Jesus, Paul`'s and all the apostles`' leader,
and still the true believer`'s guide.
And every faithful follower of Jesus has this to say, and that not boastingly, that,
revelation has not ceased, nor is the Gospel hid, but to them that are lost by unbelief,
and who will not, or do not believe in the light of Christ, and in the sufficiency of it;
such must lie down in sorrow.
And to all who assert,
that there is no state of redemption from sin to be witnessed on this side of the grave,
I say, such have great reason to cry out, that they are full of putrefied sores,
and that they have no soundness in them.
These are sad complaints indeed; and how can it be otherwise,
while they plead for the devil`'s kingdom, which is sin and darkness, and confusion?
Oh! therefore, let me prevail with all to be reconciled to God, by believing in his Son,
whom he has appointed Heir of all things,
and by and through whom you may find acceptance, who is the Advocate indeed;
of which a remnant are living witnesses, blessed be God,
even those who have believed in the power of his inward appearance,
in which there is victory obtained over the world, the flesh, and the devil.

Oh! happy souls, that can thus believe in his name;
these shall be baptized with Christ`'s own baptism,
even with the Holy Spirit and with fire; that is,
by his pure spirit and word entering into their hearts,
as a fire against every appearance of evil, to burn it up,
and destroy it in its first appearance.

Oh! that the children of men would be wise, and fear God, and call upon his name,
while the door of mercy is open, that their souls may live.
For this I heartily pray, because I have tasted of the good word of God,
and have known something of the power of the world to come: and,
having tasted both of his mercy and judgment,
I can do no less than invite and entreat all to be faithful to the Lord,
and to all his requirings; that, in the winding up of all things,
God may have the praise, who is everlastingly worthy;
and our poor souls find the joy and comfort that none else can give or take away.
