[short="Testimony from Tottenham Monthly Meeting"]
== A Testimony from our Monthly Meeting at Tottenham, held the 25th day of the Eleventh month, 1720, concerning our deceased Friend, Alice Hayes; with an account of some of her dying sayings.

Our dear and well-beloved Friend, Alice Hayes,
was born of honest parents at Rickmansworth, in Hertfordshire, in the year 1657,
who educated and brought her up in the profession of the church of England,
as appears by her own account.

It pleased the Lord to make known his truth to her, by that servant of the Lord,
Elizabeth Stamper, sister to Francis Stamper, about the year 1680.
She was called forth into the work of the ministry,
and concerned to visit the churches in several parts of this nation.

She also travelled through Holland into Germany, as far as Frederickstadt,
and had excellent service.
Many have been reached and convinced by her ministry,
it being in the demonstration and power of the Spirit.
She removed out of Hertfordshire, and came to settle in Tottenham, about the year 1712.
And we had true unity with her,
both with respect to her innocent exemplary life and conduct,
and also her gift in the ministry, in which she was made very serviceable to us,
for the encouragement of Friends to faithfulness, in every branch of their testimony.
And she frequently attended our meeting of business,
in which she often gave very solid and seasonable advice.

Being at the Yearly Meeting in London, in the year 1720, she was taken ill;
but her love being strong to her Friends there, she stayed some days,
and then returned to her house at Tottenham, and grew weaker and weaker,
till she quietly departed this life like a lamb.
During the time of her sickness she gave much good advice and counsel to her family,
as also to others who came to visit her,
and dropped many sweet sayings of her comfortable enjoyment of the Lord`'s presence;
some of which follow.

James Dickinson and Peter Fearon came to visit her, in their return from London,
and had a comfortable time with her;
and she broke forth in admiration of the Lord`'s goodness that attended his servants,
and at that time had enlarged their hearts together; and said,
"`She trusted the Lord would be with them, and be with her to the end,
and help her safely through;`" desiring to be remembered
by them in their near approaches to the Lord,
when separated; as also to give her love to her dear Friends in the north,
not expecting to see them again; but said, "`All will be well.`"
She was resigned to the Lord`'s time;
and desired that the Lord would conduct them safe to their families,
and give them plentifully to enjoy of his peace,
for their labours in his work and service.

At another time a Friend of Tottenham coming to visit her, and others coming in,
she said, "`Oh! love one another, and the Lord make you a living people unto himself,
and preserve you in perfect love and unity.
I am,`" said she, "`in perfect love to all people,`" with many more weighty expressions;
and then desired Friends "`to give her up freely to her God;`" saying,
"`I am willing to die, and I hope it will not be long: but, oh!
I would go exactly in the Lord`'s time: and all that I desire is,
that the Lord`'s presence may be continued to me,
and then I fear not the pinching time--the hour of death.
My God is my resurrection, and my glory; here is my strength, my refuge,
and I am thoroughly resigned to his will: and it will be but a little time,
and my soul shall sing praise to the Lord on mount Zion, with the redeemed,
out of the reach of trouble.`"

Some Friends being come to visit her at another time,
she broke forth in a tender frame of spirit, and said, "`I do wait on my God;
and he is a God of everlasting lovingkindness,
and has been good to my soul all my life long:`" and then said, "`Friends,
do not put off making your peace with him till you come upon a dying bed.
Here is enough to do, to labour under the afflictions of the body;
I would not be without the favour of God now for all the world.
The Lord, the God of Abraham, of Isaac, and of Jacob, my God and your God, bless you,
and be a God to you in all your trials, for he has been so to me;
a sufficient helper in times of trouble.`"

Several young people being with her at another time,
she tenderly advised them "`to be good, and serve God faithfully,
and not put off the great work of their day to the last;
but timely to prepare for a dying hour; that,`" said she,
"`you may have oil in your lamps, and be in readiness whenever that time shall come.
It has been the joy of my heart to go to a meeting, and to meet with the Lord there;
but much more joy it will be to my soul, to meet with him in heaven,
and to have a place in his kingdom.
Through mercy, I am under no terror of death, but am in true peace:
oh! blessed be my God forever, his goodness is exceeding large.
I would praise him for his goodness, but that I am very weak, and desire,
if it be his will, not to see the light of another day, my affliction being great:
but all in his own time.`"
She then broke forth in prayer, that her passage might be made easy;
desiring to be supported under her affliction, which at times was very sharp;
yet she bore it all with great patience, still looking to the Lord, her comforter,
under the deepest provings, and often said, "`Oh!
Lord Jesus, receive my spirit, for I long to be with you my Saviour;
yet let me not offend you, but patiently wait your time.`"

She greatly desired, "`that the Lord might bless her children,
and that they might serve him faithfully in their generation,`"
and was often deeply engaged in spirit before the Lord for them,
who were all, save one, at a great distance from her;
desiring "`they might be men of truth, fearing God.`"

A few days before her death,
some Friends of Tottenham sat down to wait on the Lord God with her:
his love was largely manifested, and sprung up as a fresh spring;
and after a Friend had been concerned in supplication, she broke forth and said,
"`Oh! love; this is love that may be felt: my God, your goodness is wonderful;
my soul praises you for the overflowings of your love at this time;
an opportunity unexpected:`" with many more sweet heavenly expressions.
She tenderly acknowledged the kindness of her friends in that visit;
and taking leave in brokenness of spirit, desired "`the Lord to be with them,
and to strengthen them, to be valiant for his truth,
and to keep their meetings in his name and power:`" saying,
"`Oh! what comfortable times we have often had in our week-day meetings:
how have our cups overflowed with the love of our
heavenly Father!`" with more very affecting expressions;
exhorting "`to abide in the unity of the Spirit of Christ,
every member keeping in its proper place, and concerned for the honour of truth,
in maintaining good order in the church,`" etc.

At another time, near her end,
she desired "`her dear love might be remembered to all Friends, wishing well to them,
and to their posterity.`"
She desired those about her, when they should see her going to breathe her last,
"`to be very still and inward with the Lord in their spirits,
breathing for her easy passage:`" adding, "`all will be well: I am going home,
I am going home: I have done with the world, and all that is in it;
but breathe that the Lord may pour out his spirit upon a young generation,
that they may serve him in cleanness of heart.`"
And further said, that "`she had fought the good fight,
and should obtain the crown immortal:`" adding, "`My beloved is mine, and I am his:
he is my all in all.`"
And then she prayed sweetly, "`Oh! everlasting God, and mighty Jehovah,
send the angel of your power and presence to conduct my soul into your heavenly mansion,
my holy King, where there is joy and rejoicing, and singing of praises forevermore.
Into your arms, Lord Jesus Christ, I offer up my soul and spirit.`"

The last words she was heard to say, her voice being low, were,
"`The Lord my God will help me.`"

She was a lover of peace and unity, and promoted it to the utmost of her understanding.
Her ministry was very plain and powerful; but, to the disconsolate,
it often dropped like rain, and ran like oil to the wounded:
she had a word in season to most or all conditions, and often in our week-day meetings,
her advice has dropped like dew.
Our cups have been filled, and have overflowed with praise to the great Fountain,
and we have been encouraged in a holy perseverance in the way of the Lord.

But she is now removed,
and has no doubt entered into that joy and bliss prepared for the righteous.

She greatly desired that the Lord`'s good presence might attend the meeting at her interment;
which was eminently answered.
The body was accompanied by Friends and others to Winchmore-hill meeting,
where several living testimonies were borne, the way of salvation opened,
and many hearts tendered by the Lord`'s power.

She departed this life the 8th day of the seventh month, 1720,
aged about sixty-three years, and was buried the 13th of the same,
in Friends`' burying-ground, at Winchmore-hill.

[.the-end]
The End.
